### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by rjcrystal** [phoenix367/AAMToolbox#2]
hello i am getting this make error i have installed boost 
here is the log

no matching function for call to ‘min(std::vector<aam::TrainModelInfo>::size_type, unsigned int)’
                 boost::thread::hardware_concurrency());
                                                      ^
src/AAMFunctions2D.cpp:559:54: note: candidates are:
In file included from /usr/include/c++/4.8/bits/char_traits.h:39:0,
                 from /usr/include/c++/4.8/ios:40,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iostream:39,
                 from src/AAMFunctions2D.cpp:26:
/usr/include/c++/4.8/bits/stl_algobase.h:193:5: note: template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:193:5: note:   template argument deduction/substitution failed:
src/AAMFunctions2D.cpp:559:54: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘unsigned int’)
                 boost::thread::hardware_concurrency());
                                                      ^
In file included from /usr/include/c++/4.8/bits/char_traits.h:39:0,
                 from /usr/include/c++/4.8/ios:40,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iostream:39,
                 from src/AAMFunctions2D.cpp:26:
/usr/include/c++/4.8/bits/stl_algobase.h:239:5: note: template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/4.8/bits/stl_algobase.h:239:5: note:   template argument deduction/substitution failed:
src/AAMFunctions2D.cpp:559:54: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long unsigned int’ and ‘unsigned int’)
                 boost::thread::hardware_concurrency());
                                                      ^
make[2]: *** [build/Debug/GNU-Linux-x86/src/AAMFunctions2D.o] Error 1
make[2]: Leaving directory `/home/rjcrystal/research/AAMToolbox'
make[1]: *** [.build-conf] Error 2
make[1]: Leaving directory `/home/rjcrystal/research/AAMToolbox'
make: *** [.build-impl] Error 2

**Comment by phoenix367** [comment]
I added cmake support to build aam toolbox. Potentially it fixes the issue. You can download a new version and try to build again.
