### ISSUE TITLE
Does not build - some missing dependency

### ISSUE THREAD

**Issue by or-else** [phoenix367/AAMToolbox#3]
$ make
Scanning dependencies of target AAM
[ 33%] Building CXX object CMakeFiles/AAM.dir/src/AAM.cpp.o
[ 66%] Building CXX object CMakeFiles/AAM.dir/src/DetectFace.cpp.o
[100%] Building CXX object CMakeFiles/AAM.dir/src/MatlabIO.cpp.o
Linking CXX executable AAM
/usr/bin/ld: CMakeFiles/AAM.dir/src/MatlabIO.cpp.o: undefined reference to symbol 'inflate'
/lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/AAM.dir/build.make:165: recipe for target 'AAM' failed
make[2]: **\* [AAM] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/AAM.dir/all' failed
make[1]: **\* [CMakeFiles/AAM.dir/all] Error 2
Makefile:72: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by phoenix367** [comment]
Changed build process. Wontfix.
